<root>      = (title | author | email)+
<meta-header> = '#+'
<meta-title>   = <meta-header> 'TITLE:' #"\s*"
<meta-author>  = <meta-header> 'AUTHOR:' #"\s*"
<meta-email>  = <meta-header> 'EMAIL:' #"\s*"
(* #+TITLE: content *)
title        = <meta-title>  #'.+'?
author       = <meta-author>  #'.+'?
email        = <meta-email>  #'.+'?
(*  *)
<tab>    = #'\t'
<space>    = #'\s'
<spaces>   = space+
<newline> = #'\n'